#!/bin/sh

#make arduPi_pi2.o
#make  SX1272.o
#make lora_gateway_pi2.o
#make lora_gateway_pi2
#sudo ./lora_gateway_pi2 --mode 1

mkdir bin
CFLAGS="-DPABOOST -DMAX_DBM=14 -DRASPBERRY -DRASPBERRY2 -DIS_RCV_GATEWAY"
g++ -c lib/arduPi2.cpp -o bin/arduPi2.o
g++ -c lib/SX1272.cpp -o bin/SX1272.o
g++ $CFLAGS -c lora_gateway.cpp -o bin/lora_gateway.o
g++ -lrt -lpthread bin/lora_gateway.o bin/arduPi2.o bin/SX1272.o -o lora_gateway
sudo ./lora_gateway --mode 1

