#!/bin/csh -f
#
print_land ANNOTATE.DP
print_land CHECKCLASSIC2LEVEL.DP
print_land CHECKINPUT.DP
print_land CHECKKYX.DP
print_land COMPUTESTATS.DP
print_land CONF.DP
print_land CORE.DP
print_land DETERMINE_K.DP
print_land DEX10STEPANALYSIS.DP
print_land DEXBP.DP
print_land DEXCONT.DP
print_land DEXCP.DP
print_land DEXCRSDP.DP
print_land DEXEP.DP
print_land DEXGETLEVELCODED.DP
print_land DEXHPP.DP
print_land DEXIEM.DP
print_land DEXKNBOX.DP
print_land DEXKNBOXLEE.DP
print_land DEXMP.DP
print_land DEXODP.DP
print_land DEXPLOTDEFPLOTSET.DP
print_land DEXPLOTINIT.DP
print_land DEXRIGHTMARGIN.DP
print_land DEXSP.DP
print_land DEXSTAT2.DP
print_land DEXWRITELEVELCODED.DP
print_land DEXWRITELEVEL.DP
print_land DEXWRITEPROJECT.DP
print_land DEXYP64.DP
print_land DEXYP.DP
print_land DIGIT.DP
print_land EST.DP
print_land PLOTERRORBARS.DP
print_land RIGHTMARGINFACTORSANDLEVELS.DP
print_land SETCIRCLE.DP
print_land TAGCORN.DP
print_land UPPERLEFT.DP
print_land YATESGEN.DP
