#!/bin/csh
mv annotate.dp ANNOTATE.DP
mv checkclassic2level.dp CHECKCLASSIC2LEVEL.DP
mv checkinput.dp CHECKINPUT.DP
mv checkkyx.dp CHECKKYX.DP
mv computestats.dp COMPUTESTATS.DP
mv conf.dp CONF.DP
mv core.dp CORE.DP
mv determine_k.dp DETERMINE_K.DP
mv dex10stepanalysis.dp DEX10STEPANALYSIS.DP
mv dexbp.dp DEXBP.DP
mv dexcont.dp DEXCONT.DP
mv dexcp.dp DEXCP.DP
mv dexcrsdp.dp DEXCRSDP.DP
mv dexep.dp DEXEP.DP
mv dexgetlevelcoded.dp DEXGETLEVELCODED.DP
mv dexhpp.dp DEXHPP.DP
mv dexiem.dp DEXIEM.DP
mv dexknbox.dp DEXKNBOX.DP
mv dexknboxlee.dp DEXKNBOXLEE.DP
mv dexmp.dp DEXMP.DP
mv dexodp.dp DEXODP.DP
mv dexplotdefplotset.dp DEXPLOTDEFPLOTSET.DP
mv dexplotinit.dp DEXPLOTINIT.DP
mv dexrightmargin.dp DEXRIGHTMARGIN.DP
mv dexsp.dp DEXSP.DP
mv dexstat2.dp DEXSTAT2.DP
mv dexwritelevelcoded.dp DEXWRITELEVELCODED.DP
mv dexwritelevel.dp DEXWRITELEVEL.DP
mv dexwriteproject.dp DEXWRITEPROJECT.DP
mv dexyp64.dp DEXYP64.DP
mv dexyp.dp DEXYP.DP
mv digit.dp DIGIT.DP
mv est.dp EST.DP
mv ploterrorbars.dp PLOTERRORBARS.DP
mv rightmarginfactorsandlevels.dp RIGHTMARGINFACTORSANDLEVELS.DP
mv setcircle.dp SETCIRCLE.DP
mv tagcorn.dp TAGCORN.DP
mv upperleft.dp UPPERLEFT.DP
mv yatesgen.dp YATESGEN.DP
