#!/bin/sh

export VISUALWORKS=/home/netgen/vw8.3pul
export SOURCE_PATH=/media/netgen/CST17PUL

cd /home/netgen/vw8.3pul/image
/home/netgen/vw8.3pul/bin/linux86/visual /home/netgen/vw8.3pul/image/install.im
